### ISSUE TITLE
Mod Suggestion: Darker Depths

### ISSUE THREAD

**Issue by CheetahCyberBoi** [VazkiiMods/crucial2#229] opened 2021-09-12 19:58 UTC
Darker Depths is a cool cave biome mod that I feel could fit into the pack pretty nicely. It adds many new building blocks + new ore gen in its biomes. Combining this with the other cave mods in the pack could make the underground very interesting to explore and mine in. https://www.curseforge.com/minecraft/mc-mods/darker-depths

**Comment by QuietObserver** [comment] 2021-09-17 15:36
I totally agree with this, if darker depths were added and maybe cockroaches and/or cave centipedes were enabled caves would not only have different strategies and noise(like currently), but also new content and aesthetics.

**Comment by StrangerSon71** [comment] 2021-09-18 01:15
Dupe of a closed issue by me. Even closed Caves and Cliffs Backport by the same dev, I think he just likes Quark cave biomes.

**Closed** 2021-09-23 17:29 UTC
