### ISSUE TITLE
Console Errors and lag when auto-saving (presumably?)

### ISSUE THREAD

**Issue by funketh** [VazkiiMods/crucial2#215] opened 2021-08-26 20:16 UTC
I'm consistently getting these errors whenever the game is auto saving.
And it feels like I get heavy frame drops whenever this happens. (not sure if this is caused by the errors)
```
[21:43:31] [Server thread/ERROR] [minecraft/WorldSettingsImport]: Error adding element: Base value out of range: 256 [-10-128]
[21:43:32] [Server thread/ERROR] [minecraft/WorldSettingsImport]: Error adding element: Base value out of range: 256 [-10-128]
[21:43:32] [Server thread/ERROR] [minecraft/WorldSettingsImport]: Error adding element: Base value out of range: 256 [-10-128]
```

**Comment by evanbones** [comment] 2021-08-28 03:05
Caused by Infernal Expansion, apparently it's been fixed on their github but hasn't been released yet

**Comment by funketh** [comment] 2021-09-24 01:10
Just wanted to add that you can use this version which includes the fix:
https://github.com/infernalexp/Infernal-Expansion/issues/261#issuecomment-907872233

**Closed** 2022-05-04 12:46 UTC
